version: '3.9'

services:
  vision-matcher:
    build: .
    image: vision-matcher:test
    container_name: vision-matcher
    ports:
      - '5123:5123'
    environment:
      NODE_ENV: production
      PORT: 5123
