{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ tpl .Values.ingress.name . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{ tpl .Values.ingress.host . }}
      secretName: {{ tpl .Values.ingress.tlsSecret . }}
  rules:
    - host: {{ tpl .Values.ingress.host . }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.service.name }}
                port:
                  number: {{ .Values.service.ports.app }}
---
{{- end }}

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Values.app.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.ports.app }}
      targetPort: {{ .Values.service.ports.app }}

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.statefulset.name }}
  namespace: {{ .Release.Namespace }}
spec:
  serviceName: {{ .Values.statefulset.serviceName }}
  replicas: {{ .Values.statefulset.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
        - name: {{ .Values.statefulset.containerName }}
          image: io2060/vision-matcher:{{ .Chart.Version }}
          imagePullPolicy: {{ .Values.statefulset.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.ports.app }}
          resources:
            requests:
              memory: {{ .Values.statefulset.resources.requests.memory | quote }}
              cpu: {{ .Values.statefulset.resources.requests.cpu | quote }}
            limits:
              memory: {{ .Values.statefulset.resources.limits.memory | quote }}
              cpu: {{ .Values.statefulset.resources.limits.cpu | quote }}
          volumeMounts:
            - name: vision-matcher-storage
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: vision-matcher-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.statefulset.storage }}
