apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.namespace.name }}
spec:
  selector:
    app: {{ .Values.app.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.ports.redis }}
      targetPort: {{ .Values.service.ports.redis }}

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.statefulset.name }}
  namespace: {{ .Values.namespace.name }}
spec:
  serviceName: {{ .Values.statefulset.serviceName }}
  replicas: {{ .Values.statefulset.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
        - name: {{ .Values.statefulset.containerName }}
          image: io2060/vision-matcher:{{ .Chart.Version }}
          imagePullPolicy: {{ .Values.statefulset.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.ports.redis }}
          volumeMounts:
            - name: vision-matcher-storage
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: vision-matcher-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.statefulset.storage }}
