global:
  domain: dev.example.io  

app:
  name: vision-matcher

statefulset:
  name: vision-matcher
  serviceName: vision-matcher
  replicas: 1
  containerName: vision-matcher
  pullPolicy: Always
  storage: 1Gi
  resources:
    requests:
      cpu: 300m
      memory: 896Mi
    limits:
      cpu: "1"
      memory: 1536Mi

service:
  name: vision-matcher-service
  ports:
    app: 5123

ingress:
  enabled: true
  name: vision-matcher-ingress
  host: vm.{{ .Values.global.domain }}
  tlsSecret: vm.{{ .Values.global.domain }}-cert
