
app:
  name: vision-matcher

statefulset:
  name: vision-matcher
  serviceName: vision-matcher
  replicas: 1
  containerName: vision-matcher
  pullPolicy: Always
  storage: 1Gi

service:
  name: vision-matcher-service
  ports:
    redis: 5123
